### ISSUE TITLE
save songs played into shared playlist

### ISSUE THREAD

**Issue by timball** [dasevilla/rdiodj#21] opened 2015-01-21 22:34 UTC
not sure how the ownship of that playlist would be ... maybe everyone in room is a "collaborator" to a playlist owned by starter of the "room" . but it would be super sweet to add all played tracks to a playlist for future reference and curation ... 

ooh can rdiodj play a playlist ? 

nope . new bug .

**Comment by dasevilla** [comment] 2015-01-23 07:08
Duplicate of #7

**Closed by dasevilla** 2015-01-23 07:08 UTC
Labels: enhancement
